[project]
name = "raw-to-tiff-for-alexa-mini"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "grishjarta6 laptop", email = "sitepolongovna@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pillow>=12.3.0",
]

[project.scripts]
raw-to-tiff-for-alexa-mini = "raw_to_tiff_for_alexa_mini:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
